      - name: Deploy na EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "Usuário EC2: $EC2_USER"
          echo "Host EC2 configurado"

          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2_key "$EC2_USER@$EC2_HOST" << EOF
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

            docker pull ghcr.io/cassianomc/portfolio-devops:latest

            docker stop portfolio || true
            docker rm portfolio || true

            docker run -d \
              --name portfolio \
              --restart always \
              -p 80:80 \
              ghcr.io/cassianomc/portfolio-devops:latest
          EOF