name: Deploy Portfolio

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/cassianomc/portfolio-devops:latest
  CONTAINER_NAME: portfolio

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Login no GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build da imagem Docker
        run: docker build -t $IMAGE_NAME .

      - name: Push da imagem para o GHCR
        run: docker push $IMAGE_NAME

      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key

      - name: Deploy na EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "Usuário EC2: $EC2_USER"
          echo "Host EC2 configurado"

          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2_key "$EC2_USER@$EC2_HOST" << EOF
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

            docker pull ghcr.io/cassianomc/portfolio-devops:latest

            docker stop portfolio || true
            docker rm portfolio || true

            docker run -d \
              --name portfolio \
              --restart always \
              -p 80:80 \
              ghcr.io/cassianomc/portfolio-devops:latest
          EOF